AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'tmp/**/*'
    - 'pkg/**/*'
    - 'spec/fixtures/**/*'
    - 'dist/vscode-extension/**/*'
    - 'dist/github-action/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 200

Metrics/ModuleLength:
  Max: 200

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'secrets_dev.gemspec'

Style/IfUnlessModifier:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'bin/secrets-dev'
